# config.yaml

agent_defaults:
  energy: 50
  money: 100
  epsilon: 0.1

shops:
  CheapShop:
    cost: 8
    energy_gain: 25
    success_rate: 0.6
  PremiumShop:
    cost: 15
    energy_gain: 40
    success_rate: 0.9

actions:
  move:
    energy_cost: 15
  rest:
    energy_gain: 10
